spring:
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:blog}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true